/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:60195daf-347b-471f-8925-34ac71987247",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_MgIszbP79",
    "aws_user_pools_web_client_id": "134j0o6fl1vrpjjmf81gs38kud",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hgfhzdk5qjgapd5tk6kzkzenxm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pzqa62miknhxlgp5afuz4wyef4",
    "aws_user_files_s3_bucket": "amplifyapp0001135157-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
